# Generated by Django 3.2.6 on 2021-08-05 12:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='standard',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'extendeduser__type': 'Teacher'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.standard')),
                ('student', models.ForeignKey(limit_choices_to={'extendeduser__type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='subjects',
            field=models.ManyToManyField(to='teacher.Subject'),
        ),
    ]
