# Generated by Django 3.2.6 on 2021-08-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_attendancerecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
