# Generated by Django 3.2.6 on 2021-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_attendancerecord_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='day',
            field=models.DateField(),
        ),
    ]
